language: go

os:
  - linux

dist: xenial

before_install:
  # Queue (Beanstalkd)
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - go get github.com/BurntSushi/toml
  - go get github.com/rakyll/statik
  - go get github.com/rakyll/statik/fs
  - go get -d -t -v ./... && go build -v ./...
  - beanstalkd -v
  - beanstalkd -l 127.0.0.1 -p 11300 &

go:
  - 1.16.x
  - 1.17.x

env:
  jobs:
    - GOARCH=amd64
    - GOARCH=386

script:
  - go vet ./...
  - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
